apiVersion: v1
kind: Pod
metadata:
  name: catalog-front-pod
  labels:
    name: catalog-front-pod
    app: pets
spec:
  containers:
    - name: catalog-front-pod
      image: nicolort/catalog-front-app:latest
      ports:
       - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-front-service
spec:
  type: ClusterIP
  ports:
    - port: 3001 # Port exposed by the service internally within the cluster
      targetPort: 3000 # Port on the pods to which traffic will be forwarded
      protocol: TCP
  selector:
    name: catalog-front-pod
    app: pets
    






