# Generated by Django 5.0.4 on 2024-04-19 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='name_pet',
            field=models.CharField(default='sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mascota',
            name='breed',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
    ]
