# Generated by Django 5.0.4 on 2024-04-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='mascotas/')),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ManyToManyField(related_name='mascotas', to='mascotas.imagenmascota'),
        ),
    ]
