# Generated by Django 5.0.4 on 2024-04-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_imagenmascota_remove_mascota_imagen_mascota_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='ImagenMascota',
        ),
    ]
