# Generated by Django 5.0.4 on 2024-04-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_remove_mascota_birth_date_pet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='birth_date_pet',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='breed_pet_pet',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='especie_pet_pet',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='name_pet',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
